#! /bin/bash

set -eo pipefail

. ./functions.sh

. ~/python3_venv/bin/activate

nproc=16

aimratio=--aimratio
export CONTAMID=$(./ciaostr)_contamfit_some

datadir=$(./datadir)
fitdir="$datadir/fits/$CONTAMID"
resdir="$fitdir/results"
mkdir -p "$resdir"
\ln -Tfs ./results "$fitdir/$CONTAMID" 2>/dev/null

# This cannot be done in contamfit due to resulting race condition
# when multiple instances run in parallel.
\ln -Tfs "$contelem_l" ./mymodels 2>/dev/null

for det in i3 s3; do
    obsids=$(obsids $det)

    false && env CONTAMFILE=NONE parallel -j $nproc ./specextract ::: $obsids

    parallel -j $nproc bash -x ./contamfit $aimratio ::: $obsids

    contamfits_txt="$resdir/contamfits_${det}.txt"
    perl ./compile_fit_results.pl contam $obsids | tee "$contamfits_txt"
    ./plot_contamfits "$contamfits_txt"
    psmerge_xspec contam $det

    python3 \
	./plot_fit_results.py contam $det \
	-p "$resdir/params_${det}_simul.pdf"

    python3 \
	./plot_fit_results.py contam $det \
	-p "$resdir/params_${det}.pdf" --no-simul

done
