#! /bin/bash

set -eo pipefail

. ./functions.sh

. ~/python3_venv/bin/activate

nproc=16

aimratio=--aimratio
resp120C='--120C'

aimratio=
resp120C=

export CONTAMID=$(./ciaostr)_contamfit

datadir=$(./datadir)
fitdir="$datadir/fits/$CONTAMID"
resdir="$fitdir/results"
mkdir -p "$resdir"
\ln -Tfs ./results "$fitdir/$CONTAMID" 2>/dev/null

# This cannot be done in contamfit due to resulting race condition
# when multiple instances run in parallel.
\ln -Tfs "$contelem_l" ./mymodels 2>/dev/null

for det in i3 s3; do
    obsids=$(obsids $det)

    true && env CONTAMFILE=NONE parallel -j $nproc ./specextract $resp120C ::: $obsids

    #
    # simul fits must be done separately since a race condition may
    # occur: while the separate obsid norm-fit energy-shifted pi
    # files are being copied to the output directory, the simul fit is
    # trying to use them
    #
    simul_obsids=$(perl -F= -anle 'print $F[0]' ../data/simul/$det)
    parallel -j $nproc bash -x ./contamfit $aimratio $resp120C ::: $obsids
    parallel -j $nproc bash -x ./contamfit $aimratio $resp120C ::: $simul_obsids

    contamfits_txt="$resdir/contamfits_${det}.txt"
    perl ./compile_fit_results.pl contam $obsids | tee "$contamfits_txt"
    ./plot_contamfits "$contamfits_txt"
    psmerge_xspec contam $det

    python3 \
	./plot_fit_results.py contam $det \
	-p "$resdir/params_${det}_simul.pdf"

    python3 \
	./plot_fit_results.py contam $det \
	-p "$resdir/params_${det}.pdf" --no-simul

done
