#! /bin/bash

set -eo pipefail

SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. "$SCRIPTDIR/functions.sh"

[ $# -ge 1 ] && obsids="$@" || obsids=$(obsids $DET)

. ~/.bash_aliases
shopt -s expand_aliases

ciao 1>/dev/null

for obsid in $obsids; do
    obsid=$(printf %05d $((10#"$obsid")))
    reprodir="$datadir/$obsid/repro"
    evt2="$reprodir/acisf${obsid}_repro_evt2.fits"
    fp_temp=$(printf %.2f $(dmkeypar "$evt2" fp_temp ec+))
    echo $fp_temp $obsid
done | sort |
    while read fp_temp obsid; do
	echo -e "$obsid\t$fp_temp"
    done
