#! /bin/bash

# Adapted from
# /data/paul11/plucinsk/chandra/data/e0102/I3/scripts/gainfit_S3_cstat.pl
# Requires NoLine_v1.3.1_{line,coco}.fits in
# $HEADAS/../spectral/modelData, which were obtained from
# /data/paul11/plucinsk/chandra/data/e0102

set -eo pipefail

[ -z "$CONTAMID" ] && {
    echo "CONTAMID is not set, exiting" 1>&2
    exit 1
}

SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. "$SCRIPTDIR/functions.sh"

[ $# -ge 1 ] && obsids="$@" || obsids=$(obsids $DET)

emin=0.35
emax=1.6

. ~/.bash_aliases
shopt -s expand_aliases

heainit

model="$SCRIPTDIR/rgspn_mod_tbabs_tbvarabs_2apec_line_ratios_jd_v1.9.xcm"

[ "$FITMG" = 'yes' ] && {
    thaw37='thaw 37'
}

for obsid in $obsids; do
    obsid=$(printf %05d $((10#"$obsid")))
    fitdir="$datadir/fits/$CONTAMID/$obsid"

    pi="$fitdir/${obsid}.pi"
    bkg_pi="$fitdir/${obsid}_bkg.pi"
    log_file="$fitdir/${obsid}_gainfit.log"
    save_file="$fitdir/${obsid}_gainfit.save"
    fit_file="$fitdir/${obsid}_gainfit.xcm"
    ps_file="$fitdir/${obsid}_gainfit.ps"
    rm -f "$save_file"

    #cd $fitdir

    cat - <<EOP >$fit_file
log $log_file
query yes
statistic cstat
data $pi
ignore **:**-$emin
ignore **:$emax-**
@$model
statistic cstat
thaw 1
$thaw37
fit
fit
fit
fit
setplot energy
setplot xlog off
cpd ${ps_file}/cps
plot data resid
cpd /null
gain fit
1
0
fit
fit
fit
fit
show free
show fit
statistic chi
weight model
save all $save_file
EOP
    xspec < "$fit_file"
done

