#! /bin/bash

set -eo pipefail

SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. "$SCRIPTDIR/functions.sh"

[ $# -ge 1 ] && obsids="$@" || obsids=$(obsids $DET)

imagedir="$datadir/images"
mkdir -p "$imagedir"

for obsid in $obsids; do
    obsid=$(printf %05d $((10#$obsid)))
    regdir="$datadir/reg"
    srcreg="$regdir/src.reg"
    bkgreg="$regdir/bkg/${obsid}_bkg.reg"

    [ -f "$srcreg" ] || {
	echo "not found: '$srcreg'" 2>&1
	exit 1
    }

    [ -f "$bkgreg" ] || {
	echo "not found: '$bkgreg'" 2>&1
	exit 1
    }

    imagefile="$imagedir/$obsid.jpg"
    [ -f "$imagefile" ] && continue
    evt2=$(\ls $datadir/$obsid/repro/acisf${obsid}_repro_evt2.fits)
    ds9 \
	"$evt2" \
	-regions "$bkgreg" \
	-regions "$srcreg" \
	-scale mode 99.5 \
	-pan to 01:04:01.996 -72:01:53.44 wcs \
	-bin factor 2 \
	-cmap heat \
	-saveimage "$imagedir/$obsid.jpg" \
	-exit
done
