#! /bin/bash

set -eo pipefail

[ $# -ge 1 ] || {
    echo "Usage: $0 [obsid1 obsid2 ...]" 1>&2
    exit
}
obsids="$@"

SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

. $SCRIPTDIR/functions.sh

imagedir="$datadir/images"
mkdir -p "$imagedir"

for obsid in $obsids; do
    obsid=$(printf %05d $((10#$obsid)))
    regdir="$datadir/reg"
    srcreg="$regdir/src.reg"
    bkgreg="$regdir/bkg/${obsid}_bkg.reg"
    evt2=$(\ls $datadir/$obsid/repro/acisf${obsid}_repro_evt2.fits)
    ds9 \
	"$evt2" \
	-regions "$bkgreg" \
	-regions "$srcreg" \
	-scale mode 99.5 \
	-pan to 01:04:01.996 -72:01:53.44 wcs \
	-bin factor 2 \
	-cmap heat \
	-saveimage "$imagedir/$obsid.jpg" \
	-exit
done
