#! /bin/bash

# Adapted from
# /data/paul11/plucinsk/chandra/data/e0102/I3/scripts/fit_energies.pl
# Requires NoLine_v1.3.1_{line,coco}.fits in
# $HEADAS/../spectral/modelData, which were obtained from
# /data/paul11/plucinsk/chandra/data/e0102

set -eo pipefail

TEMP=$(getopt -o 'h' --long 'tieNe9,nothawcons,help' -- "$@") || {
	echo 'Terminating...' >&2
	exit 1
}
eval set -- "$TEMP"
unset TEMP

thawcons=yes

while true; do
    case "$1" in
	'-h' | '--help')
	    echo "Usage: $0 [-h|--help] [--tieNe9] [--nothawcons] [obsid1 obsid2 ...]" >&2
	    exit
	    ;;
	'--tieNe9')
	    tieNe9=yes; shift; continue
	    ;;
	'--nothawcons')
	    thawcons=no; shift; continue
	    ;;
	'--')
	    shift; break
	    ;;
	*)
	    echo 'Internal error, terminating' >&2
	    exit 1
	    ;;
    esac
done

[ -z "$CONTAMID" ] && {
    echo "CONTAMID is not set, exiting" 1>&2
    exit 1
}

SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. "$SCRIPTDIR/functions.sh"

[ $# -ge 1 ] && obsids="$@" || obsids=$(obsids $DET)

emin=0.35
emax=1.6

. ~/.bash_aliases
shopt -s expand_aliases

heainit

model="$SCRIPTDIR/rgspn_mod_tbabs_tbvarabs_2apec_line_ratios_jd_v1.9.xcm"

for obsid in $obsids; do
    obsid=$(printf %05d $((10#"$obsid")))
    fitdir="$datadir/fits/$CONTAMID/$obsid"

    shift_script="$fitdir/${obsid}_line_shifts.xcm"

    pi="$fitdir/${obsid}.pi"
    bkg_pi="$fitdir/${obsid}_bkg.pi"
    log_file="$fitdir/${obsid}_linefit.log"
    save_file="$fitdir/${obsid}_linefit.save"
    fit_file="$fitdir/${obsid}_linefit.xcm"
    ps_file="$fitdir/${obsid}_linefit.ps"
    pdf_file="$fitdir/${obsid}_linefit.pdf"
    rm -f "$save_file"

    o7_error='error max 4.0 1. 119'
    o8_error='error max 4.0 1. 116'

    o7_freeze=
    o8_freeze=

    year=$(obsid_year $obsid)

    [ $year -gt ${o7_cutoff} ] && {
	o7_freeze='freeze 127 119'
	o7_error=''
    }
    [ $year -gt ${o8_cutoff} ] && {
	o8_freeze='freeze 118 116'
	o8_error=''
    }

    [ "$tieNe9" = yes ] && Ne9norm="newpar 67=61*$(Ne_ratio $obsid)"

    thawCons='thaw 1'
    [ "$thawcons" = no ] && thawCons=''

    cat - <<EOP >$fit_file
log $log_file
query yes
statistic cstat
data $pi
ignore **:**-$emin
ignore **:$emax-**
@$model
@$shift_script
statistic cstat
$thawCons
thaw 37
$Ne9norm
${o7_freeze}
${o8_freeze}
fit
fit
fit
fit
thaw 119, 116, 65, 59, 29
${o7_freeze}
${o8_freeze}
fit
fit
fit
fit
setplot energy
setplot xlog off
cpd ${ps_file}/cps
plot data resid
cpd /null
show free
show fit
error max 4.0 1. 29
error max 4.0 1. 59
error max 4.0 1. 65
$o8_error
$o7_error
show free
show fit
statistic chi
weight model
save all $save_file
EOP
    xspec < "$fit_file"
    ps2pdf "$ps_file" "$pdf_file"
done

