#! /bin/bash

#
# Adapted from
#
# /data/paul11/plucinsk/chandra/data/e0102/I3/scripts/plot_shifted_fits.pl
#

set -eo pipefail

[ $# -eq 1 ] || {
    echo Usage: $0 shiftfits_table
    exit
}

f="$1"

[ -z "$CONTAMID" ] && {
    echo "CONTAMID is not set, exiting" 1>&2
    exit 1
}

chip=I3
emin=0.35
emax=1.6

SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. "$SCRIPTDIR/functions.sh"

. ~/.bash_aliases
shopt -s expand_aliases

heainit

plot_shiftfit() {
    [ $# -eq 5 ] || {
	echo "Usage: $0 obsid cstat dof redchi chi" 1>&2
	return 1
    }
    local obsid="$1"
    local cstat="$2"
    local dof="$3"
    local redchi="$4"
    local chi="$5"

    obsid=$(printf %05d $((10#"$obsid")))
    fitdir="$datadir/fits/$CONTAMID/$obsid"
    savefile="$fitdir/${obsid}_shiftfit.save"
    plotfile="$fitdir/${obsid}_shiftfit_plot.xcm"
    psfile="$fitdir/${obsid}_shiftfit.ps"

    cd $fitdir

    cat - <<EOP >"$plotfile"
@$savefile
setplot energy
setplot xlog off
iplot data resid
rescale x $emin $emax
label otop CONTAMID=$CONTAMID, Gain correction applied to the data
label top $chip, ObsID $obsid, C-stat=$cstat, dof=$dof, Q-stat=$chi, reduced Q stat=$redchi
hardcopy $psfile/cps
EOP
    xspec < "$plotfile"
    cd -
}

while IFS= read -r line; do
    [[ "$line" =~ ^# ]] && continue
    read -r obsid cstat dof redchi chi <<<$(perl -anle 'print join " ", @F[0, 20..23]' <<< "$line")
    plot_shiftfit $obsid $cstat $dof $redchi $chi
done < "$f"
