#! /bin/bash

#
# Adapted from
#
# /data/paul11/plucinsk/chandra/data/e0102/I3/scripts/plot_shifted_fits.pl
#

set -eo pipefail

[ $# -eq 1 ] || {
    echo Usage: $0 shiftfits_table
    exit
}

f="$1"

[ -z "$CONTAMID" ] && {
    echo "CONTAMID is not set, exiting" 1>&2
    exit 1
}

chip=${DET^^}
emin=0.35
emax=1.6

SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. "$SCRIPTDIR/functions.sh"

. ~/.bash_aliases
shopt -s expand_aliases

heainit

plot_shiftfit() {
    [ $# -eq 5 ] || {
	echo "Usage: $0 obsid cstat dof redchi chi" 1>&2
	return 1
    }
    local obsid=$(printf %05d $((10#"$1")))
    local cstat="$2"
    local dof="$3"
    local redchi="$4"
    local chi="$5"

    local fitdir="$datadir/fits/$CONTAMID/$obsid"
    local savefile="$fitdir/${obsid}_shiftfit.save"
    local plotfile="$fitdir/${obsid}_shiftfit_plot.xcm"
    local psfile="$fitdir/${obsid}_shiftfit.ps"

    simul=$(\grep ^$obsid "$srcdir/../data/simul/$DET" || :)
    [ -n "$simul" ] && obsid=$(perl -F= -anle 'print $F[1]' <<<"$simul")

    local date=$(obsid_date ${obsid%%,*})

    cd $fitdir

    cat - <<EOP >"$plotfile"
@$savefile
setplot energy
setplot xlog off
iplot data resid
rescale x $emin $emax
label otop $CONTAMID, Gain correction applied to the data
label top $chip $obsid: Date=$date C-stat=$cstat dof=$dof Q-stat=$chi reduced Q-stat=$redchi
hardcopy $psfile/cps
EOP
    xspec < "$plotfile"
    cd -
}

while IFS= read -r line; do
    [[ "$line" =~ ^# ]] && continue
    read -r obsid cstat dof redchi chi <<<$(perl -anle 'print join " ", @F[0, -4..-1]' <<< "$line")
    plot_shiftfit $obsid $cstat $dof $redchi $chi
done < "$f"
