#! /bin/bash

# adapted from /data/paul11/plucinsk/chandra/data/e0102/I3/scripts/repro.pl

set -eo pipefail

[ $# -ge 1 ] || {
    echo Usage: $0 obsid1 obsid2 ... 1>&2
    exit 1
}
obsids="$@"

SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

. ~/.bash_aliases
shopt -s expand_aliases

ciao

. "$SCRIPTDIR/functions.sh"
. "$SCRIPTDIR/tmppdir.sh"

for obsid in $obsids; do
    obsid=$(printf %05d $((10#"$obsid")))
    punlearn ardlib
    punlearn chandra_repro
    chandra_repro \
	"$datadir/$obsid" \
	"$datadir/$obsid/repro" \
	check_vf_pha=no \
	set_ardlib=no \
	verbose=3 \
	clob+
done

