#! /bin/bash

#
# Adapted from
#
# /data/paul11/plucinsk/chandra/data/e0102/I3/scripts/fit_shifted_pi.pl
#
# Requires NoLine_v1.3.1_{line,coco}.fits in
# $HEADAS/../spectral/modelData, which were obtained from
# /data/paul11/plucinsk/chandra/data/e0102
#

set -eo pipefail

TEMP=$(getopt -o 'h' --long 'tieNe9,help' -- "$@") || {
	echo 'Terminating...' >&2
	exit 1
}
eval set -- "$TEMP"
unset TEMP

while true; do
    case "$1" in
	'-h' | '--help')
	    echo "Usage: $0 [-h|--help] [--tieNe9] [obsid1 obsid2 ...]" >&2
	    exit
	    ;;
	'--tieNe9')
	    tieNe9=yes; shift; continue
	    ;;
	'--')
	    shift; break
	    ;;
	*)
	    echo 'Internal error, terminating' >&2
	    exit 1
	    ;;
    esac
done

[ -z "$CONTAMID" ] && {
    echo "CONTAMID is not set, exiting" 1>&2
    exit 1
}

SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. "$SCRIPTDIR/functions.sh"

[ $# -ge 1 ] && obsids="$@" || obsids=$(obsids $DET)

emin=0.35
emax=1.6

. ~/.bash_aliases
shopt -s expand_aliases

heainit

model="$SCRIPTDIR/rgspn_mod_tbabs_tbvarabs_2apec_line_ratios_jd_v1.9.xcm"

simul_pi_files() {
    local obsid="$1"
    local match=$(\grep --no-filename ^"$obsid" "$SCRIPTDIR"/../data/simul/[is]3)
    if [ -n "$match" ]; then
	cut -d= -f2 <<<$match | perl -F, -anle 'print for @F'  |
	    while read obs; do
		echo -n "$datadir/fits/$CONTAMID/$obs/${obs}_energy_shift.pi "
	    done
	echo
    fi
}

fit_obsid() {
    local obsid=$(printf %05d $((10#"$1")))
    local fitdir="$datadir/fits/$CONTAMID/$obsid"

    # for simul fit ObsIDs (e.g., 99999), the fit directory might not yet exist
    mkdir -p "$fitdir"

    local pi=$(simul_pi_files $obsid)
    [ -z "$pi" ] && pi="$fitdir/${obsid}_energy_shift.pi"

    local log_file="$fitdir/${obsid}_shiftfit.log"
    local save_file="$fitdir/${obsid}_shiftfit.save"
    local fit_file="$fitdir/${obsid}_shiftfit.xcm"
    local ps_file="$fitdir/${obsid}_shiftfit.ps"
    rm -f "$save_file"

    o7_freeze=
    o7_error='error max 4.0 1. 127'

    o8_freeze=
    o8_error='error max 4.0 1. 118'

    year=$(obsid_year $obsid)

    [ $year -gt ${o7_cutoff} ] && {
	o7_freeze='freeze 127'
	o7_error=
    }
    [ $year -gt ${o8_cutoff} ] && {
	o8_freeze='freeze 118'
	o8_error=
    }

    Ne9conf='error max 4.0 1. 67'
    [ "$tieNe9" = yes ] && {
	Ne9conf=
	Ne9norm="newpar 67=61*$Ne_ratio"
    }

    cat - <<EOP >$fit_file
log $log_file
query yes
data $pi
ignore **:**-$emin
ignore **:$emax-**
@$model
statistic cstat
thaw 1
thaw 37
$Ne9norm
${o7_freeze}
${o8_freeze}
fit
fit
fit
fit
setplot energy
setplot xlog off
cpd ${ps_file}/cps
plot data resid
cpd /null
show free
show fit
error max 4.0 1. 1
error max 4.0 1. 37
error max 4.0 1. 61
$Ne9conf
${o7_error}
${o8_error}
show free
show fit
statistic chi
weight model
save all $save_file
EOP
    xspec < "$fit_file"
}

for obsid in $obsids; do
    fit_obsid $obsid
    match=$(\grep --no-filename =$obsid $SCRIPTDIR/../data/simul/[is]3 || :)
    [ -n "$match" ] && {
	simul_obs=$(perl -F= -anle 'print $F[0]' <<<$match)
	fit_obsid $simul_obs
    } || :
done
