#! /bin/bash

# adapted from
# /data/paul11/plucinsk/chandra/data/e0102/I3/scripts/specextract.pl

set -eo pipefail

TEMP=$(getopt -o 'h' --long '120C,help' -- "$@") || {
	echo 'Terminating...' >&2
	exit 1
}
eval set -- "$TEMP"
unset TEMP

resp120C=

while true; do
    case "$1" in
	'-h' | '--help')
	    echo "Usage: $0 [-h|--help] [--120C] [obsid1 obsid2 ...]" >&2
	    exit
	    ;;
	'--120C')
	    resp120C=yes; shift; continue
	    ;;
	'--')
	    shift; break
	    ;;
	*)
	    echo 'Internal error, terminating' >&2
	    exit 1
	    ;;
    esac
done

[ -z "$CONTAMID" ] && {
    echo "CONTAMID is not set, exiting" 1>&2
    exit 1
}

SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. "$SCRIPTDIR/functions.sh"

[ $# -ge 1 ] && obsids="$@" || obsids=$(obsids $DET)

. ~/.bash_aliases
shopt -s expand_aliases

ciao

. "$SCRIPTDIR/tmppdir.sh"

[ -z "$CONTAMFILE" ] &&
    CONTAMFILE=$(\ls $CALDB/data/chandra/acis/contam/acisD1999-08-13contam*.fits | tail -1)

srcreg="$datadir/reg/src.reg"

for obsid in $obsids; do
    obsid=$(printf %05d $((10#"$obsid")))

    reprodir="$datadir/$obsid/repro"
    fitdir="$datadir/fits/$CONTAMID/$obsid"
    bkgreg="$datadir/reg/bkg/${obsid}_bkg.reg"
    evt2="$reprodir/acisf${obsid}_repro_evt2.fits"
    [ "$resp120C" = yes ] &&  evt2="${evt2/evt2.fits/evt2-120C.fits}"
    asol_stack=$(\ls -1 "$reprodir/../primary/"pcad*asol1.fits*  | perl -le 'chomp(@l=<>); print join ",", @l')
    pbk=$(\ls -1 "$reprodir/"*pbk0.fits*)
    msk=$(\ls -1 "$reprodir/acisf${obsid}"_*_msk1.fits*)
    bpix="$reprodir/acisf${obsid}_repro_bpix1.fits"

    mkdir -p $fitdir

    punlearn ardlib
    punlearn specextract

    acis_set_ardlib "$bpix"

    for i in $(seq 0 9); do
	pset ardlib AXAF_ACIS${i}_CONTAM_FILE="$CONTAMFILE[AXAF_CONTAM$(( i+1 ))]"
    done

    specextract \
	infile="$evt2[sky=region($srcreg)]" \
	outroot="$fitdir/${obsid}_" \
	bkgfile="$evt2[sky=region($bkgreg)]" \
	asp="$asol_stack" \
	mskfile="$msk" \
	badpixfile="$bpix" \
	weight=yes \
	correct=no \
	verbose=3 \
	grouptype=NUM_CTS \
	binspec=30 \
	clobber=yes \
	combine=no \
	bkgresp=yes

    srcpi="$fitdir/${obsid}.pi"
    srcarf="${srcpi/.pi/.arf}"
    srcrmf="${srcpi/.pi/.rmf}"

    bkgpi="${srcpi/.pi/_bkg.pi}"
    bkgarf="${bkgpi/.pi/.arf}"
    bkgrmf="${bkgpi/.pi/.rmf}"

    # set full pathnames ancr,resp,back

    punlearn dmhedit
    dmhedit \
	infile="$srcpi" \
	filelist=none \
	operation=add \
	key=backfile \
	value="'$bkgpi'"

    punlearn dmhedit
    dmhedit \
	infile="$srcpi" \
	filelist=none \
	operation=add \
	key=respfile \
	value="'$srcrmf'"

    punlearn dmhedit
    dmhedit \
	infile="$srcpi" \
	filelist=none \
	operation=add \
	key=ancrfile \
	value="'$srcarf'"

    punlearn dmhedit
    dmhedit \
	infile="$bkgpi" \
	filelist=none \
	operation=add \
	key=respfile \
	value="'$bkgrmf'"

    punlearn dmhedit
    dmhedit \
	infile="$bkgpi" \
	filelist=none \
	operation=add \
	key=ancrfile \
	value="'$bkgarf'"

done
    
